// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZELuG5bxFkUKX3Yp0g8B1cio6Of1opp0',
    appId: '1:55270167333:web:2496137eb1821c045bc0cc',
    messagingSenderId: '55270167333',
    projectId: 'todoapp-8bb5b',
    authDomain: 'todoapp-8bb5b.firebaseapp.com',
    storageBucket: 'todoapp-8bb5b.firebasestorage.app',
    measurementId: 'G-3N3TEZ4W0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoFQihvCCGs7RcAIgfUkqqf87GnD8dD9g',
    appId: '1:55270167333:android:19c18a2d34808dbd5bc0cc',
    messagingSenderId: '55270167333',
    projectId: 'todoapp-8bb5b',
    storageBucket: 'todoapp-8bb5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiIOjlmqPfHhmkDYh2tKWgMCaj_7I5cCs',
    appId: '1:55270167333:ios:f71b2e76f02724b75bc0cc',
    messagingSenderId: '55270167333',
    projectId: 'todoapp-8bb5b',
    storageBucket: 'todoapp-8bb5b.firebasestorage.app',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiIOjlmqPfHhmkDYh2tKWgMCaj_7I5cCs',
    appId: '1:55270167333:ios:f71b2e76f02724b75bc0cc',
    messagingSenderId: '55270167333',
    projectId: 'todoapp-8bb5b',
    storageBucket: 'todoapp-8bb5b.firebasestorage.app',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZELuG5bxFkUKX3Yp0g8B1cio6Of1opp0',
    appId: '1:55270167333:web:dfea52a181344cf65bc0cc',
    messagingSenderId: '55270167333',
    projectId: 'todoapp-8bb5b',
    authDomain: 'todoapp-8bb5b.firebaseapp.com',
    storageBucket: 'todoapp-8bb5b.firebasestorage.app',
    measurementId: 'G-VKT3SYZSQ9',
  );
}
